# Precisamos de um problema.
## https://en.wikipedia.org/wiki/Test_functions_for_optimization
###Booth function
f(x,y) = (x+2y-7)^2 + (2x+y-5)^2

# Achar o valor mínimo da função Booth!

In [ ]:
tam_pop = 10
dimensao = 2
limites = [-10,10]


In [ ]:
import numpy as  np
populacao = np.random.uniform(low=limites[0], high=limites[1], size=(tam_pop,dimensao))

In [ ]:
populacao

array([[-3.77934648,  4.88875016],
       [-7.76791816, -7.02214197],
       [-2.82081722,  0.02924188],
       [-5.70260113, -7.04415068],
       [ 3.33267612, -2.20058085],
       [ 2.03888352, -4.74994158],
       [-8.7461574 ,  8.3844186 ],
       [ 1.94323239, -7.21256816],
       [ 4.11210179,  1.04098736],
       [ 7.25837927, -1.51817008]])

In [ ]:
populacao[0]

array([-3.77934648,  4.88875016])

In [ ]:
def pontuacao(x, y):
  return (x + 2*y -7)**2 + (2*x + y - 5)**2

In [ ]:
def calcular_pontuacao(populacao):
  return [pontuacao(x[0],x[1]) for x in populacao ]

In [ ]:
p = calcular_pontuacao(populacao)
p

[59.83171825179132,
 1589.5851572729991,
 207.9260302948582,
 1267.6246081370828,
 65.38692924323995,
 241.29407509381355,
 200.07860919334516,
 448.8685789916045,
 18.8413664418425,
 71.69448404966279]

In [ ]:
populacao

array([[-3.77934648,  4.88875016],
       [-7.76791816, -7.02214197],
       [-2.82081722,  0.02924188],
       [-5.70260113, -7.04415068],
       [ 3.33267612, -2.20058085],
       [ 2.03888352, -4.74994158],
       [-8.7461574 ,  8.3844186 ],
       [ 1.94323239, -7.21256816],
       [ 4.11210179,  1.04098736],
       [ 7.25837927, -1.51817008]])

In [ ]:
# objetivo é criar uma lista que poporcionalmente os indivídos com menor pontuacao 
# possuem maior numero de elementos

def calculo_roleta(pontuacoes):
  roleta = []
  total = sum(pontuacoes)
  for i, valor in enumerate(pontuacoes):
    repeticao = round(abs(total/(valor + 1)))
    for r in range(repeticao):
      roleta.append(i)
  return roleta
  

In [ ]:
resultado = calculo_roleta(p)
resultado

In [ ]:
import random
def crossover(populacao,g1,g2):
  return [populacao[g1][random.randint(0, 1)], populacao[g2][random.randint(0, 1)]]   


In [ ]:
import numpy as np
import random

tam_pop = 10
dimensao = 2
limites = [-10,10]
mutacao = 0.1
repeticao = 100

populacao = np.random.uniform(low=limites[0], high=limites[1], size=(tam_pop,2))
for count in range(repeticao):
  filhos = []
  print("Repetição", count)
  pontuacoes = calcular_pontuacao(populacao)
  indice = pontuacoes.index(min(pontuacoes))
  print("Menor valor:", min(pontuacoes), " Individuo:", populacao[indice])
  roleta = calculo_roleta(pontuacoes)
  for tam in range(tam_pop):
    genitor1 = random.choice(roleta)
    genitor2 = random.choice(roleta)
    filho = crossover(populacao, genitor1, genitor2)
    if (random.random() < 0.1):
      # print("Entrou")
      filho[0] = random.randint(limites[0], limites[1])
      filho[1] = random.randint(limites[0], limites[1])
    filhos.append(filho)
  populacao = np.array(filhos) 



